In [5]:
import json
from pathlib import Path
from datetime import date
import pandas as pd

In [6]:
paris_summer = pd.read_csv("./raw/olympics/olympics_paris2024.csv",encoding="utf-8")
winter_summer_games = pd.read_csv("./raw/olympics/olympics_history.csv",encoding="utf-8")

In [8]:
paris_summer

,country_code,country,country_long,Gold Medal,Silver Medal,Bronze Medal,Total
0,USA,United States,United States of America,40,44,42,126
1,CHN,China,People's Republic of China,40,27,24,91
2,JPN,Japan,Japan,20,12,13,45
3,AUS,Australia,Australia,18,19,16,53
4,FRA,France,France,16,26,22,64
...,...,...,...,...,...,...,...
87,PER,Peru,Peru,0,0,1,1
88,QAT,Qatar,Qatar,0,0,1,1
89,SGP,Singapore,Singapore,0,0,1,1
90,SVK,Slovakia,Slovakia,0,0,1,1
91,ZAM,Zambia,Zambia,0,0,1,1

In [9]:
winter_summer_games

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total
0,1896,1896 Summer Olympics,1,Greece,GRE,10,18,19,47
1,1900,1900 Summer Olympics,2,France,FRA,31,41,40,112
2,1900,1900 Summer Olympics,2,United States,USA,20,13,15,48
3,1904,1904 Summer Olympics,3,United States,USA,80,85,83,248
4,1908,1908 Summer Olympics,5,Great Britain,GBR,56,51,39,146
...,...,...,...,...,...,...,...,...,...
1802,2008,2008 Summer Olympics,53,Australia,AUS,14,15,17,46
1803,2008,2008 Summer Olympics,53,Cuba,CUB,3,10,17,30
1804,2012,2012 Summer Olympics,54,Japan,JPN,7,14,17,38
1805,2016,2016 Summer Olympics,59,Great Britain,GBR,27,23,17,67
1806,2020,2020 Summer Olympics,61,Japan,JPN,27,14,17,58

In [10]:
paris_summer_processed = (
    paris_summer
    .rename(columns={
    "country_code": "country_noc",
    "Gold Medal": "gold",
    "Silver Medal": "silver",
    "Bronze Medal": "bronze",
    "Total": "total"
    })
)

paris_summer_processed = paris_summer_processed.groupby("country")[["gold","silver","bronze","total"]].sum()

In [11]:
paris_summer_processed

               gold  silver  bronze  total
country
AIN               1       3       1      5
Albania           0       0       2      2
Algeria           2       0       1      3
Argentina         1       1       1      3
Armenia           0       3       1      4
...             ...     ...     ...    ...
Uganda            1       1       0      2
Ukraine           3       5       4     12
United States    40      44      42    126
Uzbekistan        8       2       3     13
Zambia            0       0       1      1

[92 rows x 4 columns]

In [12]:
paris_summer_processed.reset_index(inplace=True)

In [13]:
# Separar por jogos de verão/inverno
summer = winter_summer_games[winter_summer_games["edition"].str.contains("Summer")]
winter = winter_summer_games[winter_summer_games["edition"].str.contains("Winter")]

summer = pd.concat([summer, paris_summer_processed])

summer_medals = summer.groupby("country")["total"].sum()
winter_medals = winter.groupby("country")["total"].sum()

In [16]:
summer_medals = summer_medals.sort_values(ascending=False)
winter_medals = winter_medals.sort_values(ascending=False)

In [19]:
summer_medals = (
    summer.groupby("country")[["gold","silver","bronze","total"]]
    .sum()
    .sort_values("total", ascending=False)
)

winter_medals = (
    winter.groupby("country")[["gold","silver","bronze","total"]]
    .sum()
    .sort_values("total", ascending=False)
)

total_medals = (
    winter_summer_games.groupby("country")[["gold","silver","bronze","total"]]
    .sum()
    .sort_values("total", ascending=False)
)

In [20]:
summer_medals

                              gold  silver  bronze  total
country
United States                 1110     885     786   2781
Soviet Union                   395     319     296   1010
Great Britain                  305     345     342    992
France                         247     283     307    837
Germany                        249     277     298    824
...                            ...     ...     ...    ...
Sudan                            0       1       0      1
Turkmenistan                     0       1       0      1
Tonga                            0       1       0      1
Togo                             0       0       1      1
United States Virgin Islands     0       1       0      1

[163 rows x 4 columns]

In [21]:
winter_medals

                                       gold  silver  bronze  total
country
Norway                                  148     134     123    405
United States                           113     122      95    330
Germany                                 112     104      70    286
Austria                                  71      88      91    250
Canada                                   77      72      76    225
Soviet Union                             78      57      59    194
Sweden                                   65      51      60    176
Finland                                  45      65      65    175
Switzerland                              63      47      58    168
Netherlands                              53      49      45    147
Italy                                    42      43      56    141
France                                   41      42      55    138
Russian Federation                       46      39      35    120
East Germany                             39      36      35    110
Republic of Korea                        33      30      16     79
People's Republic of China               22      32      23     77
Japan                                    17      28      31     76
ROC                                       8      18      23     49
West Germany                             11      15      13     39
Czechia                                  10      11      13     34
Great Britain                            12       5      17     34
Czechoslovakia                            2       8      15     25
Slovenia                                  4       8      12     24
Unified Team                              9       6       8     23
Poland                                    7       7       9     23
Belarus                                   8       7       5     20
Australia                                 6       7       6     19
Croatia                                   4       6       1     11
Latvia                                    1       3       6     10
Slovakia                                  4       4       2     10
Liechtenstein                             2       2       6     10
Hungary                                   2       2       6     10
Ukraine                                   3       2       4      9
Kazakhstan                                1       3       4      8
Belgium                                   2       2       4      8
Estonia                                   4       2       2      8
Bulgaria                                  1       2       3      6
New Zealand                               2       2       2      6
Spain                                     1       1       3      5
Yugoslavia                                0       3       1      4
Luxembourg                                0       2       0      2
Democratic People's Republic of Korea     0       1       1      2
Denmark                                   0       1       0      1
Mixed team                                1       0       0      1
Romania                                   0       0       1      1
Uzbekistan                                1       0       0      1

In [22]:
total_medals

                              gold  silver  bronze  total
country
United States                 1195     969     845   3009
Soviet Union                   473     376     355   1204
Germany                        355     377     366   1098
Great Britain                  312     339     337    988
France                         287     308     356    951
...                            ...     ...     ...    ...
Sudan                            0       1       0      1
Turkmenistan                     0       1       0      1
Tonga                            0       1       0      1
Togo                             0       0       1      1
United States Virgin Islands     0       1       0      1

[154 rows x 4 columns]

In [25]:
total_medals.to_csv("./bronze/olympics_medals.csv")

### Modalidades_1986_2024

In [26]:
modalidades_paris = pd.read_csv("./raw/medals/medals_paris.csv")

In [27]:
modalidades_paris

,medal_type,medal_code,medal_date,name,gender,discipline,event,event_type,url_event,code,country_code,country,country_long
0,Gold Medal,1.0,2024-07-27,Remco EVENEPOEL,M,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1903136,BEL,Belgium,Belgium
1,Silver Medal,2.0,2024-07-27,Filippo GANNA,M,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1923520,ITA,Italy,Italy
2,Bronze Medal,3.0,2024-07-27,Wout van AERT,M,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1903147,BEL,Belgium,Belgium
3,Gold Medal,1.0,2024-07-27,Grace BROWN,W,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1940173,AUS,Australia,Australia
4,Silver Medal,2.0,2024-07-27,Anna HENDERSON,W,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1912525,GBR,Great Britain,Great Britain
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,Silver Medal,2.0,2024-08-09,KALEYN Boryana,W,Rhythmic Gymnastics,Individual All-Around,ATH,NaN,1548948,BUL,Bulgaria,Bulgaria
1040,Bronze Medal,3.0,2024-08-09,RAFFAELI Sofia,W,Rhythmic Gymnastics,Individual All-Around,ATH,NaN,1923694,ITA,Italy,Italy
1041,Gold Medal,1.0,2024-08-09,THIAM Nafissatou,W,Athletics,Women's Heptathlon,ATH,NaN,1903112,BEL,Belgium,Belgium
1042,Silver Medal,2.0,2024-08-09,JOHNSON-THOMPSON Katarina,W,Athletics,Women's Heptathlon,ATH,NaN,1977926,GBR,Great Britain,Great Britain
1043,Bronze Medal,3.0,2024-08-09,VIDTS Noor,W,Athletics,Women's Heptathlon,ATH,NaN,1895596,BEL,Belgium,Belgium

In [29]:
modalidades_paris["discipline"].unique()

<StringArray>
[         'Cycling Road',                'Diving',               'Fencing',
                  'Judo',          'Rugby Sevens',              'Shooting',
              'Swimming',               'Archery',          'Canoe Slalom',
 'Cycling Mountain Bike',         'Skateboarding',   'Artistic Gymnastics',
            'Equestrian',          'Table Tennis', 'Cycling BMX Freestyle',
                'Rowing',             'Triathlon',             'Athletics',
             'Badminton',    'Cycling BMX Racing',               'Sailing',
                'Tennis', 'Trampoline Gymnastics',                'Boxing',
                  'Golf',        '3x3 Basketball',         'Cycling Track',
               'Surfing',             'Wrestling',     'Artistic Swimming',
        'Sport Climbing',             'Taekwondo',         'Weightlifting',
          'Canoe Sprint',              'Football',                'Hockey',
     'Marathon Swimming',      'Beach Volleyball',              'Breaking',
            'Volleyball',            'Basketball',              'Handball',
     'Modern Pentathlon',            'Water Polo',   'Rhythmic Gymnastics']
Length: 45, dtype: str

In [30]:
modalidades_olimpiadas_1986_2024 = pd.read_csv("./raw/results/olympics_results.csv")

In [33]:
modalidades_olimpiadas_1986_2024["sport"].unique()

<StringArray>
[                     'Golf',                      'Judo',
                      'Luge',                      'Polo',
                     'Bandy',                     'Kendo',
                     'Roque',                     'Rugby',
                     'Wushu',                    'Boules',
 ...
       'Equestrian Dressage',       'Equestrian Eventing',
       'Equestrian Vaulting',       'Military Ski Patrol',
       'Rhythmic Gymnastics',      'Cross Country Skiing',
     'Cycling BMX Freestyle',     'Cycling Mountain Bike',
 'Australian Rules Football', 'Short Track Speed Skating']
Length: 112, dtype: str

### Atletas por sexo

In [ ]:
atletas_olimpiadas = pd.read_csv("./raw/athletes/athletes_olympics.csv")
atletas_paris = pd.read_csv("./raw/athletes/athletes_paris.csv")

In [36]:
atletas_olimpiadas

,athlete_id,name,sex,birth_date,birth_year,height,weight,country,country_noc,description,special_notes
0,2303707,A. Sansores,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
1,2303703,Álvaro Ledón,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
2,921722,Abelardo Cuevas,Male,NaN,NaN,NaN,NaN,Cuba,CUB,"Abelardo Cuevas was a Cuban oboist, hornist, s...",NaN
3,2303702,V. Fernández,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
4,2303738,A. F. Ruiz,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
155856,141672,Quan Hongchan,Female,2007-03-28,2007.0,NaN,NaN,People's Republic of China,CHN,NaN,NaN
155857,144431,Kokona Hiraki,Female,2008-08-26,2008.0,NaN,NaN,Japan,JPN,NaN,NaN
155858,141168,Rayssa Leal,Female,2008-01-04,2008.0,147.0,35.0,Brazil,BRA,NaN,NaN
155859,143068,Sky Brown,Female,2008-07-07,2008.0,NaN,NaN,Great Britain,GBR,NaN,NaN
155860,146782,Hend Zaza,Female,2009-01-01,2009.0,NaN,NaN,Syrian Arab Republic,SYR,NaN,NaN

In [37]:
atletas_paris

,code,current,name,name_short,name_tv,gender,function,country_code,country,country_long,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,True,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,True,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,True,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,True,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,True,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11108,4986655,True,ADA ETO Sefora,ADA ETO S,Sefora ADA ETO,Female,Athlete,GEQ,Equatorial Guinea,Equatorial Guinea,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,9460001,True,LIUZZI Emanuela,LIUZZI E,Emanuela LIUZZI,Female,Athlete,ITA,Italy,Italy,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11110,1972077,False,BOERS Isayah,NaN,NaN,Male,Athlete,NED,Netherlands,Netherlands,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11111,1899865,False,STAUT Kevin,NaN,NaN,Male,Athlete,FRA,France,France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11112,1924402,False,CARVELL Charlie,NaN,NaN,Male,Athlete,GBR,Great Britain,Great Britain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
atletas_olimpiadas.columns

Index(['athlete_id', 'name', 'sex', 'birth_date', 'birth_year', 'height',
       'weight', 'country', 'country_noc', 'description', 'special_notes'],
      dtype='str')

In [39]:
atletas_paris.columns

Index(['code', 'current', 'name', 'name_short', 'name_tv', 'gender',
       'function', 'country_code', 'country', 'country_long', 'nationality',
       'nationality_long', 'nationality_code', 'height', 'weight',
       'disciplines', 'events', 'birth_date', 'birth_place', 'birth_country',
       'residence_place', 'residence_country', 'nickname', 'hobbies',
       'occupation', 'education', 'family', 'lang', 'coach', 'reason', 'hero',
       'influence', 'philosophy', 'sporting_relatives', 'ritual',
       'other_sports'],
      dtype='str')

In [48]:
atletas_paris_processed = atletas_paris.drop(columns=['code', 'current', 'name_short', 'name_tv',
        'country_code', "country_long",
       'nationality_long', 'nationality_code', 'height', 'weight',
       'disciplines', 'events', 'birth_place', 'birth_country',
       'residence_place', 'residence_country', 'nickname', 'hobbies',
       'occupation', 'education', 'family', 'lang', 'coach', 'reason', 'hero',
       'influence', 'philosophy', 'sporting_relatives', 'ritual',
       'other_sports'])

In [49]:
atletas_paris_processed.rename(columns={"gender":"sex"},inplace=True)

In [50]:
atletas_paris_processed

,name,sex,function,country,nationality,birth_date
0,ALEKSANYAN Artur,Male,Athlete,Armenia,Armenia,1991-10-21
1,AMOYAN Malkhas,Male,Athlete,Armenia,Armenia,1999-01-22
2,GALSTYAN Slavik,Male,Athlete,Armenia,Armenia,1996-12-21
3,HARUTYUNYAN Arsen,Male,Athlete,Armenia,Armenia,1999-11-22
4,TEVANYAN Vazgen,Male,Athlete,Armenia,Armenia,1999-10-27
...,...,...,...,...,...,...
11108,ADA ETO Sefora,Female,Athlete,Equatorial Guinea,Equatorial Guinea,2003-06-11
11109,LIUZZI Emanuela,Female,Athlete,Italy,NaN,2000-04-27
11110,BOERS Isayah,Male,Athlete,Netherlands,Netherlands,1999-06-19
11111,STAUT Kevin,Male,Athlete,France,France,1980-11-15
11112,CARVELL Charlie,Male,Athlete,Great Britain,Great Britain,2004-06-30

In [51]:
atletas_total = pd.concat([atletas_olimpiadas,atletas_paris_processed])

In [53]:
atletas_total

,athlete_id,name,sex,birth_date,birth_year,height,weight,country,country_noc,description,special_notes,function,nationality
0,2303707.0,A. Sansores,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN,NaN,NaN
1,2303703.0,Álvaro Ledón,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN,NaN,NaN
2,921722.0,Abelardo Cuevas,Male,NaN,NaN,NaN,NaN,Cuba,CUB,"Abelardo Cuevas was a Cuban oboist, hornist, s...",NaN,NaN,NaN
3,2303702.0,V. Fernández,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN,NaN,NaN
4,2303738.0,A. F. Ruiz,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11108,NaN,ADA ETO Sefora,Female,2003-06-11,NaN,NaN,NaN,Equatorial Guinea,NaN,NaN,NaN,Athlete,Equatorial Guinea
11109,NaN,LIUZZI Emanuela,Female,2000-04-27,NaN,NaN,NaN,Italy,NaN,NaN,NaN,Athlete,NaN
11110,NaN,BOERS Isayah,Male,1999-06-19,NaN,NaN,NaN,Netherlands,NaN,NaN,NaN,Athlete,Netherlands
11111,NaN,STAUT Kevin,Male,1980-11-15,NaN,NaN,NaN,France,NaN,NaN,NaN,Athlete,France
11112,NaN,CARVELL Charlie,Male,2004-06-30,NaN,NaN,NaN,Great Britain,NaN,NaN,NaN,Athlete,Great Britain

In [55]:
atletas_total.drop(columns=["birth_date","birth_year","height","weight","description","special_notes","function"],inplace=True)

In [56]:
atletas_total

,athlete_id,name,sex,country,country_noc,nationality
0,2303707.0,A. Sansores,Male,Cuba,CUB,NaN
1,2303703.0,Álvaro Ledón,Male,Cuba,CUB,NaN
2,921722.0,Abelardo Cuevas,Male,Cuba,CUB,NaN
3,2303702.0,V. Fernández,Male,Cuba,CUB,NaN
4,2303738.0,A. F. Ruiz,Male,Cuba,CUB,NaN
...,...,...,...,...,...,...
11108,NaN,ADA ETO Sefora,Female,Equatorial Guinea,NaN,Equatorial Guinea
11109,NaN,LIUZZI Emanuela,Female,Italy,NaN,NaN
11110,NaN,BOERS Isayah,Male,Netherlands,NaN,Netherlands
11111,NaN,STAUT Kevin,Male,France,NaN,France
11112,NaN,CARVELL Charlie,Male,Great Britain,NaN,Great Britain

In [57]:
atletas_total.to_csv("./bronze/olympics_athlets.csv")

### Modalidades

In [68]:
modalidades_paris = pd.read_csv("./raw/events/events_paris.csv")
modalidades_olimpicas = pd.read_csv("./raw/results/olympics_results.csv")

In [69]:
modalidades_olimpicas

,result_id,event_title,edition,edition_id,sport,result_date,result_location,result_participants,result_format,result_detail,result_description
0,40000,"Individual, Men",1900 Summer Olympics,2,Golf,2 October 1900,"Golf de Compiègne, Compiègne",12 from 3 countries,36 holes stroke play,na,"Charles Sands, of the St. Andrews Golf Club in..."
1,925229,"Individual, Handicap, Men",1900 Summer Olympics,2,Golf,3 October 1900,"Golf de Compiègne, Compiègne",19 from 4 countries,18 holes stroke play with handicaps.,na,"Al Lambert won the handicap event, playing off..."
2,40001,"Individual, Women",1900 Summer Olympics,2,Golf,3 October 1900,"Golf de Compiègne, Compiègne",10 from 3 countries,9 holes stroke play,na,The ladies’ event took place the day after the...
3,925231,"Individual, Professional, Men",1900 Summer Olympics,2,Golf,3 October 1900,"Golf de Compiègne, Compiègne",2 from 1 countries,36 holes stroke play.,na,Chevalier and Phillips were local professional...
4,926022,Individual (Second Flight Consolation Champion...,1904 Summer Olympics,3,Golf,22 – 25 September 1904,"Glen Echo Country Club, Normandy",16 from 1 countries,Single-elimination tournament.,na,na
...,...,...,...,...,...,...,...,...,...,...,...
7389,9001206,"1,500 metres, Women",2018 Winter Olympics,60,Short Track Speed Skating,17 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",36 from 17 countries,Placements 1-12 based on final and B final. D...,na,na
7390,9001157,"5,000 metres Relay, Men",2018 Winter Olympics,60,Short Track Speed Skating,13 – 22 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",34 from 8 countries,Placements 1-8 based on final and B final.,na,na
7391,9001142,"1,500 metres, Men",2018 Winter Olympics,60,Short Track Speed Skating,10 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",37 from 18 countries,Placements 1-12 based on final and B final. D...,na,na
7392,9001121,"1,000 metres, Men",2018 Winter Olympics,60,Short Track Speed Skating,13 – 17 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",32 from 14 countries,Placements 1-8 based on final and B final. De...,na,na
7393,9001221,"3,000 metres Relay, Women",2018 Winter Olympics,60,Short Track Speed Skating,10 – 20 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",37 from 8 countries,Placements 1-8 based on final and B final.,na,na

In [71]:
modalidades_paris

,event,tag,sport,sport_code,sport_url
0,Men's Individual,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
1,Women's Individual,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
2,Men's Team,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
3,Women's Team,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
4,Mixed Team,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
...,...,...,...,...,...
324,Men's Freestyle 65kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
325,Men's Freestyle 74kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
326,Men's Freestyle 86kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
327,Men's Freestyle 97kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
328,Men's Freestyle 125kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...